title: Vita brevis, args longa
email: mail@jdzhang.me
description: >- # this means to ignore newlines until "baseurl:"
    Notes of a computational biologist working in drug discovery
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jdzhang.me" # the base hostname & protocol for your site, e.g. http://example.com
github_username: Accio

# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts

include: ["_pages"]
