# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Vita brevis, args longa
email: jitao_david.zhang@roche.com
description: > # this means to ignore newlines until "baseurl:"
   Notes of a computational biologist in drug discovery
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://accio.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:  accio 

# Build settings
markdown: kramdown
## theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
  - jemoji
  - jekyll-include-cache
exclude:
  - Gemfile
  - ['*.Rmd']
  - Gemfile.lock
  - scripts

# specific for minimal-mistakes
paginate: 5 # amout of posts to show
paginate_path: /page:num/

# set page.mathjax if mathjax is needed. see _includes/scripts.html
# foot_scripts:
#  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js

author:
  name : "Jitao David Zhang"
  avatar : "/assets/images/DavidHamburg.png"
  bio : "A Computational Biologist in Drug Discovery"
  email : jitao_david.zhang@roche.com
  links:
    - label: "Github"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Accio"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Accio"
search: true

include: ["_pages"]

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

## default post layout
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true
